### ISSUE TITLE
Error running Python script in Windows

### ISSUE THREAD

**Issue by hci-yeo** [leapmotion/leapuvc#11]
In Windows, I get this error in Python 3
calibrationArray = struct.unpack('BBBBIffffffffffffffffffffffffffffffffffffI', bytes(calibrationBytes))
ValueError: bytes must be in range(0, 256)

And this error in Python 2
calibrationArray = struct.unpack('BBBBIffffffffffffffffffffffffffffffffffffI', bytes(calibrationBytes))
struct.error: unpack requires a string argument of length 156

any suggestion? Thanks.

**Comment by felixekman** [comment]
I've got the same issues as well, tried on several platforms and it all persists. I have also recalibrated several times.

**Comment by gitunit** [comment]
in line 168 of leapuvc.py change to the following:
`calibrationArray = struct.unpack('BBBBIffffffffffffffffffffffffffffffffffffI', bytes(calibrationBytes)[0:156])`
