### ISSUE TITLE
LED toggle not working

### ISSUE THREAD

**Issue by ghost** [leapmotion/leapuvc#8]
Not sure if device specific, I've checked in my Leap Motion control panel and the LED does work when viewing on the visualised debugger. 

The Toggle for the LED within the leapUVC doesn't seem to be working (I'm using python).

**Comment by ghost** [comment]
Running the Leap Calibration within leap motion control panel seems to have fixed this issue.

**Comment by jen-co** [comment]
Hi, I am having the same issue - I cannot seem to turn the LEDs on using the python cameraControlExample. They also do turn on when running the visualizer. How did you resolve the issue exactly? Did you just recalibrate the device using the Leap Motion control panel? I tried this but it didnt seem to make a difference.
